name: Deploy Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run simple test
      run: |
        # проверим, что index.html существует
        test -f index.html

        - name: Проверка наличия кнопки в index.html
      run: |
        # ищем кнопку по её id и уникальному стилю
        grep '<button[^>]*id="testButton"[^>]*style="margin-top: 200px;"' index.html
        if [ $? -ne 0 ]; then
          echo "Кнопка с id='testButton' и заданным стилем не найдена в index.html"
          exit 1
        else
          echo "Кнопка найдена в index.html"
        fi

    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v20
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        

        
        
